// AUTO-GENERATED by scripts/generateManifest.py — do not edit by hand
// Run: python3 scripts/generateManifest.py

export interface VideoClipInfo {
  file: string;
  duration: number;
  trimDuration: number;
}

export interface SequenceItem {
  type: "photo" | "video";
  file: string;           // manifest jpg name for photos, original filename for videos
  isPortrait?: boolean;   // photos only
  trimDuration?: number;  // videos only
  duration?: number;      // videos only
}

export interface DayData {
  date: string;
  dayNum: number;
  label: string;
  photos: string[];
  photoOrientations: boolean[];  // true = portrait
  videos: VideoClipInfo[];
  sequence?: SequenceItem[];     // interleaved order; falls back to photos-then-videos if absent
}

export const MEDIA_BASE = 'media/jpg';

export const DAYS: DayData[] = [
  {
    "date": "YYYY-MM-DD",
    "dayNum": 1,
    "label": "Day Label",
    "photos": [],
    "photoOrientations": [],
    "videos": [],
    "sequence": []
  }
];

export const TOTAL_DAYS = 1;
