// AUTO-GENERATED by scripts/generateManifest.py — do not edit by hand
// Run: python3 scripts/generateManifest.py

export interface VideoClipInfo {
  file: string;
  duration: number;
  trimDuration: number;
}

export interface DayData {
  date: string;
  dayNum: number;
  label: string;
  photos: string[];
  photoOrientations: boolean[];  // true = portrait — auto-detected from jpg dimensions
  videos: VideoClipInfo[];
}

export const MEDIA_BASE = 'media/jpg';

export const DAYS: DayData[] = [
  {
    "date": "YYYY-MM-DD",
    "dayNum": 1,
    "label": "Day Label",
    "photos": [],
    "photoOrientations": [],
    "videos": []
  }
];

export const TOTAL_DAYS = 1;
