#!/usr/bin/env python3
"""
Generate src/data/mediaManifest.ts from trip media files.

First run with --scan to discover dates in your media:
  python3 scripts/generateManifest.py --scan

Then fill DAY_ITINERARY below and run normally:
  python3 scripts/generateManifest.py
"""
import subprocess, json, sys, exifread
from pathlib import Path
from collections import defaultdict

# ── CUSTOMIZE ─────────────────────────────────────────────────────────────────
SRC = Path("/path/to/your/media/folder")   # flat folder with HEIC/JPG/MOV/MP4
OUT = Path("src/data/mediaManifest.ts")    # run script from project root

DAY_ITINERARY = {
    # "YYYY-MM-DD": "Day Label Here",   # fill from --scan output
}

PHOTOS_PER_DAY = 6    # auto-selected (picker.py lets you override)
MAX_VIDEOS     = 2    # max clips per day (largest file wins)
MAX_VIDEO_DUR  = 6.0  # seconds — clips trimmed to this
# ─────────────────────────────────────────────────────────────────────────────


def get_photo_date(f):
    try:
        with open(f, "rb") as fp:
            tags = exifread.process_file(fp, stop_tag="EXIF DateTimeOriginal", details=False)
            d = str(tags.get("EXIF DateTimeOriginal", ""))
            if d and d != "None":
                return d[:10].replace(":", "-")
    except:
        pass
    return None


def get_video_info(f):
    r = subprocess.run(
        ["ffprobe", "-v", "quiet", "-print_format", "json", "-show_format", "-show_streams", str(f)],
        capture_output=True, text=True,
    )
    date, duration = None, 0.0
    try:
        data = json.loads(r.stdout)
        tags = data.get("format", {}).get("tags", {})
        ct = tags.get("com.apple.quicktime.creationdate") or tags.get("creation_time", "")
        if ct and ct != "None":
            date = ct[:10]
        for s in data.get("streams", []):
            if s.get("codec_type") == "video":
                duration = round(float(s.get("duration", 0)), 2)
                break
    except:
        pass
    return date, duration


if "--scan" in sys.argv:
    print(f"Scanning {SRC} for media dates...")
    dates: dict[str, int] = {}
    files = sorted(SRC.iterdir())
    for i, f in enumerate(files):
        print(f"\r  {(i+1)*100//len(files):3d}% {f.name:<50}", end="", flush=True)
        suf = f.suffix.lower()
        date = None
        if suf in [".heic", ".jpg", ".jpeg", ".png"]:
            date = get_photo_date(f)
        elif suf in [".mov", ".mp4"]:
            date, _ = get_video_info(f)
        if date:
            dates[date] = dates.get(date, 0) + 1
    print(f"\r  Done.{' ' * 60}")
    print("\nPaste into DAY_ITINERARY:")
    for d in sorted(dates):
        print(f'    "{d}": "Day Label Here",  # {dates[d]} files')
    sys.exit(0)


photos_by_day: dict[str, list] = defaultdict(list)
videos_by_day: dict[str, list] = defaultdict(list)

files = sorted(SRC.iterdir())
total = len(files)
for i, f in enumerate(files):
    print(f"\r  {(i+1)*100//total:3d}% [{i+1}/{total}] {f.name:<45}", end="", flush=True)
    suf = f.suffix.lower()
    if suf in [".heic", ".jpg", ".jpeg", ".png"]:
        date = get_photo_date(f)
        if date and date in DAY_ITINERARY:
            jpg_name = f.stem + ".jpg" if suf == ".heic" else f.name
            photos_by_day[date].append(jpg_name)
    elif suf in [".mov", ".mp4"]:
        date, duration = get_video_info(f)
        if date and date in DAY_ITINERARY:
            videos_by_day[date].append({"file": f.name, "duration": duration or 0, "size": f.stat().st_size})

print(f"\r  Done.{' ' * 60}")

days = []
for i, (date, label) in enumerate(DAY_ITINERARY.items()):
    all_photos = photos_by_day.get(date, [])
    all_videos = videos_by_day.get(date, [])

    if len(all_photos) <= PHOTOS_PER_DAY:
        selected = all_photos
    else:
        step = len(all_photos) / PHOTOS_PER_DAY
        selected = [all_photos[int(j * step)] for j in range(PHOTOS_PER_DAY)]

    usable = [v for v in all_videos if v["duration"] >= 2.0]
    usable.sort(key=lambda v: v["size"], reverse=True)
    sel_vids = usable[:MAX_VIDEOS]
    for v in sel_vids:
        v["trimDuration"] = min(v["duration"], MAX_VIDEO_DUR)

    vids_out = [{"file": v["file"], "duration": v["duration"], "trimDuration": v["trimDuration"]} for v in sel_vids]
    # Default sequence: photos then videos (picker.py lets user reorder/interleave)
    sequence = (
        [{"type": "photo", "file": f, "isPortrait": False} for f in selected] +
        [{"type": "video", "file": v["file"], "trimDuration": v["trimDuration"], "duration": v["duration"]} for v in sel_vids]
    )

    days.append({
        "date": date,
        "dayNum": i + 1,
        "label": label,
        "photos": selected,
        "photoOrientations": [],
        "videos": vids_out,
        "sequence": sequence,
    })

ts = "\n".join([
    "// AUTO-GENERATED by scripts/generateManifest.py — do not edit by hand",
    "",
    "export interface VideoClipInfo { file: string; duration: number; trimDuration: number; }",
    "",
    "export interface SequenceItem { type: 'photo' | 'video'; file: string; isPortrait?: boolean; trimDuration?: number; duration?: number; }",
    "",
    "export interface DayData {",
    "  date: string; dayNum: number; label: string;",
    "  photos: string[]; photoOrientations: boolean[]; videos: VideoClipInfo[];",
    "  sequence?: SequenceItem[];",
    "}",
    "",
    "export const MEDIA_BASE = 'media/jpg';",
    "",
    "export const DAYS: DayData[] = " + json.dumps(days, indent=2) + ";",
    "",
    f"export const TOTAL_DAYS = {len(days)};",
])

OUT.write_text(ts)
print(f"\n✅ Written {len(days)} days to {OUT}")
for d in days:
    print(f"  {d['date']} Day {d['dayNum']}: {len(d['photos'])} photos, {len(d['videos'])} videos")
