// ── CUSTOMIZE: Replace with your trip's cities and journey legs ──────────────
// Generated by /travel-video skill — do not edit by hand if using the skill

export type TransportMode = "flight" | "car" | "boat";

export interface Leg {
  from: string;
  to: string;
  fromCoord: [number, number]; // [lng, lat]
  toCoord: [number, number];
  mode: TransportMode;
  durationS: number;
}

export interface CityInfo {
  name: string;
  coord: [number, number];
  emoji: string;
  landmark: string;
}

// Add one entry per city involved in any journey
export const CITIES: Record<string, CityInfo> = {
  home: {
    name: "Home City",
    coord: [0, 0], // [lng, lat]
    emoji: "🏙️",
    landmark: "Home Landmark",
  },
  destination: {
    name: "Destination",
    coord: [0, 0],
    emoji: "🏔️",
    landmark: "Main Landmark",
  },
};

// Journey 1: Arrival
export const JOURNEY_ARRIVAL: Leg[] = [
  {
    from: "Home City",
    to: "Destination",
    fromCoord: CITIES.home.coord,
    toCoord: CITIES.destination.coord,
    mode: "flight",
    durationS: 6,
  },
];

// Journey 2: Mid-trip (optional — delete if not needed)
export const JOURNEY_MIDTRIP: Leg[] = [
  {
    from: "Destination",
    to: "Destination",
    fromCoord: CITIES.destination.coord,
    toCoord: CITIES.destination.coord,
    mode: "car",
    durationS: 4,
  },
];

// Journey 3: Departure
export const JOURNEY_DEPARTURE: Leg[] = [
  {
    from: "Destination",
    to: "Home City",
    fromCoord: CITIES.destination.coord,
    toCoord: CITIES.home.coord,
    mode: "flight",
    durationS: 6,
  },
];

export const MODE_COLORS: Record<TransportMode, string> = {
  flight: "#f0a500",
  car: "#4fc3f7",
  boat: "#80cbc4",
};

export const MODE_DASH: Record<TransportMode, number[]> = {
  flight: [8, 6],
  car: [1, 0],
  boat: [3, 5],
};
